-- ════════════════════════════════════════════════════════════════════
--  Central de Suprimentos — estrutura do banco (PostgreSQL 13 ou mais novo)
--
--  Rodar UMA vez no banco "automacoes" (ou outro definido em DB_NAME),
--  com um usuário que possa criar schema. Pode rodar de novo sem estragar
--  nada (tudo é "if not exists").
--
--  Tudo fica no schema "suprimentos" (variável DB_SCHEMA). As regras de quem
--  pode ler e gravar ficam no servidor (servidor/app/permissoes.py): o banco
--  só guarda. O usuário do app precisa de SELECT/INSERT/UPDATE/DELETE neste
--  schema e de nada fora dele.
-- ════════════════════════════════════════════════════════════════════

create schema if not exists suprimentos;
set search_path = suprimentos;

-- Departamentos (grupos de pessoas na tela "Usuários & Permissões")
create table if not exists departamentos (
  id     uuid primary key default gen_random_uuid(),
  nome   text not null,
  cor    text,
  ordem  integer not null default 0
);

-- Pessoas do app. auth_user_id = "oid" da conta Microsoft (Entra).
create table if not exists perfis (
  id               uuid primary key default gen_random_uuid(),
  nome             text not null,
  email            text,
  telefone         text,
  auth_user_id     uuid,
  departamento_id  uuid references departamentos(id) on delete set null,
  ativo            boolean default true,
  is_admin         boolean default false,
  permissoes       jsonb,              -- lista de módulos; null = todos
  auth_legado      uuid                -- login anterior do perfil (religado sozinho no primeiro acesso)
);
alter table perfis add column if not exists auth_legado uuid;
create index if not exists perfis_auth_idx  on perfis (auth_user_id);
create index if not exists perfis_email_idx on perfis (lower(email));

-- Documentos da equipe: configurações, regras, cotações, pré-compras, avaliações etc.
-- Um registro por "tipo" (chave). O app mescla edições simultâneas antes de gravar.
create table if not exists dados_compartilhados (
  tipo           text primary key,
  dados          jsonb not null default '[]'::jsonb,
  total          integer not null default 0,
  atualizado_por text,
  atualizado_em  timestamptz default now()
);

-- Histórico das atualizações do TOTVS
create table if not exists sync_log (
  id               bigint generated by default as identity primary key,
  origem           text not null,
  total_registros  integer not null default 0,
  status           text not null,
  arquivo_nome     text,
  importado_por    text,
  mensagem         text,
  executado_em     timestamptz not null default now()
);
create index if not exists sync_log_em_idx on sync_log (executado_em desc);

-- Anotações por item de SC (responsável, prioridade, observação, OC ligada)
create table if not exists item_anotacoes (
  item_uid         text primary key,
  prioridade       boolean default false,
  responsavel_id   uuid,
  observacao       text,
  oc_vinculada     text,
  oc_vinculada_em  timestamptz,
  atualizado_por   uuid,
  atualizado_em    timestamptz default now()
);

create table if not exists sc_prioridades (
  numero_sc   text primary key,
  criado_por  uuid
);

-- Carteira de insumos de cada comprador
create table if not exists pessoa_insumos (
  id         uuid primary key default gen_random_uuid(),
  perfil_id  uuid references perfis(id) on delete cascade,
  insumo     text
);
create index if not exists pessoa_insumos_perfil_idx on pessoa_insumos (perfil_id);

-- Identidade mínima de cada item de SC (para anotações de itens fora da base local)
create table if not exists sc_itens (
  item_uid    text primary key,
  numero_sc   text not null,
  coligada    integer not null default 0,
  obra        text,
  produto     text,
  quantidade  numeric default 0,
  emissao     date,
  criado_em   timestamptz default now()
);
create index if not exists sc_itens_sc_idx on sc_itens (numero_sc);

-- Avisos dentro do app (sino)
create table if not exists notificacoes (
  id                 uuid primary key default gen_random_uuid(),
  destinatario_email text not null,
  titulo             text not null,
  mensagem           text,
  lida               boolean not null default false,
  aba                text,
  criado_por         text,
  criado_em          timestamptz not null default now()
);
create index if not exists notificacoes_dest_idx on notificacoes (lower(destinatario_email), criado_em desc);

-- Anotações e tarefas (aba Anotações)
create table if not exists anotacoes (
  id            text primary key,
  dono          uuid not null,
  compartilhada boolean not null default false,
  dados         jsonb not null,
  atualizado_em timestamptz not null default now()
);
create index if not exists anotacoes_dono_idx on anotacoes (dono);

-- Auditoria: quem mudou o quê (gravada pelo servidor)
create table if not exists auditoria (
  id          bigserial primary key,
  quando      timestamptz not null default now(),
  quem_id     uuid,
  quem_email  text,
  tabela      text not null,
  acao        text not null,
  registro    text,
  resumo      text,
  antes       jsonb,
  depois      jsonb
);
create index if not exists auditoria_quando_idx on auditoria (quando desc);

-- Chat da equipe: mensagens temporárias e quem está on-line
create table if not exists canal_eventos (
  id         bigserial primary key,
  canal      text not null,
  evento     text not null,
  de         text,
  para       text,                -- vazio = todos; preenchido = só remetente e destinatário recebem
  payload    jsonb not null default '{}'::jsonb,
  criado_em  timestamptz not null default now()
);
create index if not exists canal_eventos_idx on canal_eventos (canal, id);

-- Atualização automática do TOTVS: linhas brutas de cada consulta e o índice raw/latest.json
create table if not exists totvs_arquivos (
  caminho    text primary key,
  dados      jsonb not null,
  linhas     integer not null default 0,
  criado_em  timestamptz not null default now()
);

create table if not exists canal_presenca (
  canal      text not null,
  chave      text not null,
  meta       jsonb not null default '{}'::jsonb,
  visto_em   timestamptz not null default now(),
  primary key (canal, chave)
);
